### PR TITLE
String converter fix

### PR DESCRIPTION
**Pull request by ScottIsAFool**
Sometimes Culture can be null (especially when being used in an appbarbehaviour), the converter needs to gracefully handle this.

### CODE REVIEW

**Comment by gep13** [comment]
:+1:

**Comment by gep13** [comment]
@ScottIsAFool @PedroLamas has this been released? Thanks!

**Comment by PedroLamas** [comment]
Not yet, but it will be for 2.0.0-beta2!

**Comment by gep13** [comment]
Sweet, thank you :smile_cat:

**Pull request closed without merging**
